/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Auxiliar.Images;
import Frames.Activitie1.frmStore;
import javax.swing.JButton;

/**
 *
 * @author tady
 */
public class frmMenuGames extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuGames
     */
    public frmMenuGames() {
        initComponents();
        
        //CENTRAR EL FORMULARIO
        this.setLocationRelativeTo(null);
        
        //DAR IMAGENES A LOS BOTONES
        initializeComponents();
    }
    
    public void initializeComponents(){
        
        showBtns(btnReturn,"return");

    }
    
    public void showBtns(JButton btn,String name){
        Images img=new Images();
        img.setBtn(btn, name); //para transparencia btns=Opaque=ContentAreaFilled=(false)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGame1 = new javax.swing.JButton();
        btnGame2 = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnGame3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 36, 89));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnGame1.png"))); // NOI18N
        btnGame1.setBorder(null);
        btnGame1.setContentAreaFilled(false);
        btnGame1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGame1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 220, 210));

        btnGame2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnGame2.png"))); // NOI18N
        btnGame2.setBorder(null);
        btnGame2.setContentAreaFilled(false);
        btnGame2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGame2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 220, 210));

        btnReturn.setBackground(new java.awt.Color(246, 36, 89));
        btnReturn.setBorder(null);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 60));

        btnGame3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnGame3.png"))); // NOI18N
        btnGame3.setBorder(null);
        btnGame3.setContentAreaFilled(false);
        btnGame3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGame3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGame3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 220, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGame1ActionPerformed
        frmMemory objfrm=new frmMemory();
        this.dispose();
        objfrm.show();
    }//GEN-LAST:event_btnGame1ActionPerformed

    private void btnGame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGame2ActionPerformed
        frmConectPoints objfrm=new frmConectPoints();
        this.dispose();
        objfrm.show();
    }//GEN-LAST:event_btnGame2ActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        frmMenuNino objfrm=new frmMenuNino();
        this.dispose();
        objfrm.show();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnGame3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGame3ActionPerformed
        frmStore objfrm=new frmStore();
        this.dispose();
        objfrm.show();
    }//GEN-LAST:event_btnGame3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuGames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuGames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGame1;
    private javax.swing.JButton btnGame2;
    private javax.swing.JButton btnGame3;
    private javax.swing.JButton btnReturn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
