/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Auxiliar.Images;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author tady
 */
public class frmMenu extends javax.swing.JFrame{
    
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        
        //CENTRAR EL FORMULARIO
        this.setLocationRelativeTo(null);
        
        //DAR IMAGENES A LOS BOTONES
        initializeComponents();
        
    }
    
    public void initializeComponents(){
        showLbl(lblEspe,"espe");
        showBtns(btnExit,"exit");
        showBtns(btnChildren,"children");
        showBtns(btnParents,"parents");
    }
    
    public void showLbl(JLabel lbl,String name){
        Images image=new Images();
        image.setLbl(lbl, name);
    }
    
    public void showBtns(JButton btn,String name){
        Images image=new Images();
        image.setBtn(btn, name);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEspe = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnParents = new javax.swing.JButton();
        btnChildren = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(3, 201, 169));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEspe.setText("logo");
        jPanel1.add(lblEspe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 530, 140));

        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 90, 90));

        btnParents.setText("padres");
        btnParents.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnParents.setContentAreaFilled(false);
        btnParents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnParents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnParents, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 260, 260));

        btnChildren.setText("niño");
        btnChildren.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnChildren.setContentAreaFilled(false);
        btnChildren.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChildren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChildrenActionPerformed(evt);
            }
        });
        jPanel1.add(btnChildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 260, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChildrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChildrenActionPerformed
        frmLoginChildren objfrm=new frmLoginChildren();
        this.dispose();
        objfrm.show();
    }//GEN-LAST:event_btnChildrenActionPerformed

    private void btnParentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentsActionPerformed
        
    }//GEN-LAST:event_btnParentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChildren;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnParents;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEspe;
    // End of variables declaration//GEN-END:variables
}
