/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Auxiliar.Images;
import javax.swing.JButton;

/**
 *
 * @author tady
 */
public class frmMenuMovies extends javax.swing.JFrame {

    frmMovie objfrm=new frmMovie();
    /**
     * Creates new form frmMenuMovies
     */
    public frmMenuMovies() {
        initComponents();
        
        //CENTRAR EL FORMULARIO
        this.setLocationRelativeTo(null);
        
        //DAR IMAGENES A LOS BOTONES
        initializeComponents();
    }
    
    public void initializeComponents(){
        Images img=new Images();
        img.setLbl(lblMovieBack,"moviefon");
        
        showBtns(btnReturn,"return");
    }
    
    public void showBtns(JButton btn,String name){
        Images img=new Images();
        img.setBtn(btn, name); //para transparencia btns=Opaque=ContentAreaFilled=(false)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMovie2 = new javax.swing.JButton();
        btnMovie3 = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnMovie1 = new javax.swing.JButton();
        lblMovieBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(162, 222, 208));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMovie2.setText("Sumas");
        btnMovie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovie2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMovie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, 60));

        btnMovie3.setText("Sumas y Restas");
        btnMovie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovie3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMovie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 210, 60));

        btnReturn.setBorder(null);
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        btnMovie1.setText("Aprendiendo A contar");
        btnMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovie1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMovie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 210, 60));
        jPanel1.add(lblMovieBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovie1ActionPerformed
        this.dispose();
        objfrm.show();
        objfrm.createScene("contar");
        
    }//GEN-LAST:event_btnMovie1ActionPerformed

    private void btnMovie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovie2ActionPerformed
        this.dispose();
        objfrm.show();
        objfrm.createScene("sumar");
    }//GEN-LAST:event_btnMovie2ActionPerformed

    private void btnMovie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovie3ActionPerformed
        this.dispose();
        objfrm.show();
        objfrm.createScene("sumaryrestar");
    }//GEN-LAST:event_btnMovie3ActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        frmMenuNino objfrm=new frmMenuNino();
        this.dispose();
        objfrm.show();
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovie1;
    private javax.swing.JButton btnMovie2;
    private javax.swing.JButton btnMovie3;
    private javax.swing.JButton btnReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMovieBack;
    // End of variables declaration//GEN-END:variables
}
